package com.example.fitnessquest

val APP_PREFERENCES = "FitnessQuest"
val CURRENT_STROLLS = "CURRENT_STROLLS"
val CURRENT_CALORIES = "CURRENT_CALORIES"
val BREAKFAST_CALORIES = "BREAKFAST_CALORIES"
val LUNCH_CALORIES = "LUNCH_CALORIES"
val DINNER_CALORIES = "DINNER_CALORIES"
val CURRENT_ACTIVITY_MINS = "CURRENT_ACTIVITY_MINS"
val CURRENT_WATER_CUPS = "CURRENT_WATER_CUPS"
val FALLING_ASLEEP_TIME = "FALLING_ASLEEP_TIME"
val WAKEUP_TIME = "WAKEUP_TIME"
val CURRENT_WEIGHT = "CURRENT_WEIGHT"