package com.example.fitnessquest

val APP_PREFERENCES = "FitnessQuest"
val CURRENT_STROLLS = "CURRENT_STROLLS"
val CURRENT_CALORIES = "CURRENT_CALORIES"
val BREAKFAST_CALORIES = "BREAKFAST_CALORIES"
val LUNCH_CALORIES = "LUNCH_COLORIES"
val DINNER_CALORIES = "DINNER_CALORIES"
val CURRENT_ACTIVITY_MINS = "CURRENT_ACTIVITY_MINS"
val CURRENT_WATER_CUPS = "CURRENT_WATER_CUPS"
val SLEEP_TIME = "CURRENT_SLEEP_TIME"
val CURRENT_WEIGHT = "CURRENT_WEIGHT"