package com.example.fitnessquest

val APP_PREFERENCES = "FitnessQuest"


// step counter
val INITIAL_TOTAL_STEPS = "INITIAL_TOTAL_STEPS"

// food
val TOTAL_CALORIES = "CURRENT_CALORIES"
val BREAKFAST_CALORIES = "BREAKFAST_CALORIES"
val LUNCH_CALORIES = "LUNCH_CALORIES"
val DINNER_CALORIES = "DINNER_CALORIES"

// activity
val CURRENT_ACTIVITY_MINS = "CURRENT_ACTIVITY_MINS"

// water
val CURRENT_WATER_CUPS = "CURRENT_WATER_CUPS"

// sleep
val FALLING_ASLEEP_TIME = "FALLING_ASLEEP_TIME"
val WAKEUP_TIME = "WAKEUP_TIME"

// weight
val CURRENT_WEIGHT = "CURRENT_WEIGHT"


// rewards
val IS_SLEEP_TIME_REWARD_RECEIVED = "IS_SLEEP_TIME_REWARD_RECEIVED"
val IS_WEIGHT_REWARD_RECEIVED = "IS_WEIGHT_REWARD_RECEIVED"


// cat indicators
val CURRENT_HP = "CURRENT_HP"

